source "https://rubygems.org/"

gem "sinatra"
gem "thin"
gem "sinatra-contrib"
gem "mustermann"
gem "httparty"
gem "sinatra-slack", path: "../"

group :development do
  gem "pry"
  gem "pry-byebug"
end
