source "https://rubygems.org/"

gem "sinatra"
gem "sinatra-contrib"
gem "bcrypt"

group :development do
  gem "guard-shotgun", :git => "https://github.com/rchampourlier/guard-shotgun.git"

  gem "pry"
  gem "pry-byebug"
end